### ISSUE TITLE
Support Milestones API

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/gitlab.cr#14]
http://docs.gitlab.com/ce/api/milestones.html
- [x] List project milestones - `milestones`
- [x] Get single milestone - `milestone`
- [x] Create new milestone - `create_milestone`
- [x] Edit milestone - `edit_milestone`
- [x] Get all issues assigned to a single milestone - `milestone_issues`
